name: salary-data
channels:
  - conda-forge
dependencies:
  - python==3.9
  - alembic==1.7.4
  - bs4==4.10.0
  - click==8.0.3
  - Flask==2.0.2
  - Flask-Migrate==3.1.0
  - flask-pymongo==2.3.0
  - Flask-SQLAlchemy==2.5.1
  - glob2==0.7
  - greenlet==1.1.2
  - itsdangerous==2.0.1
  - Mako==1.1.5
  - marshmallow==3.14.1
  - numpy==1.21.4
  - pandas==1.3.4
  - psycopg2==2.9.2
  - pymongo==4.0.1
  - python-dateutil==2.8.2
  - python-dotenv==0.19.1
  - pywin32==302
  - requests==2.26.0
  - SQLAlchemy==1.4.26
  - Werkzeug==2.0.2
  - pip:
      - selenium==4.1.0
      - webdriver-manager==3.5.2
      - chromedriver-binary-auto==0.1.1
      - chromedriver-binary==98.0.4758.48.0

